[test]

# always enable coverage
coverage = true

# to require 90% line-level and function-level coverage
coverageThreshold = 0.9

coverageReporter  = ["text", "lcov"]  # default ["text"]
# coverageDir = "./reporter"  # default "coverage"
